/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Description: base data type
 * Author: duxiaobo
 * Create: 2020-4-27
 */

#ifndef __MESSAGE_CONFIG_H__
#define __MESSAGE_CONFIG_H__

#ifndef MESSAGE_ENGINE_MAX_SERVICE
#define MESSAGE_ENGINE_MAX_SERVICE 15
#endif

#ifndef MESSAGE_ENGINE_MAX_DISPATCHER
#define MESSAGE_ENGINE_MAX_DISPATCHER 10
#endif

#ifndef MESSAGE_ENGINE_DISPATCHERID_ASSIGN_START
#define MESSAGE_ENGINE_DISPATCHERID_ASSIGN_START 5
#endif

#ifndef DEFAULT_DISPATCHER_QUEUE_SIZE
#define DEFAULT_DISPATCHER_QUEUE_SIZE 20000
#endif

#ifndef DEFAULT_DISPATCHER_PRIORITY_COUNT
#define DEFAULT_DISPATCHER_PRIORITY_COUNT 4
#endif

#endif