/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Description: base data type
 * Author: duxiaobo
 * Create: 2020-4-27
 */

#ifndef __MESSAGE_TYPES_H__
#define __MESSAGE_TYPES_H__
#include "stdint.h"

typedef uint8_t ServiceID;

typedef int32_t ErrorCode;

#define ME_SUCCESS 0
#define ME_ERROR_NULL_PTR -1
#define ME_ERROR_OPER_QUEUE_FAILED -2
#define ME_ERROR_OPER_SMSEMIPHORE_FAILED -3
#define ME_ERROR_CREATE_THREAD_FAILED -4
#define ME_ERROR_NOT_SUPPORTED -5
#define ME_ERROR_DELETE_THREAD_FAILED -6
#define ME_ERROR_OPER_MUTEX_FAILED -7

#define ME_ERROR_WRONG_TYPE 1
#define ME_ERROR_MUTI_INIT_NOT_ALLOWED 2
#define ME_ERROR_INIT_QUEUE_FAILED 3
#define ME_ERROR_WRONG_STATUS 4
#define ME_ERROR_SERVICEID_CONFILT 5
#define ME_ERROR_PARA_WRONG 6
#define ME_ERROR_COMMANDID_NOT_SUPPORTED 7
#define ME_ERROR_NO_SUCH_SERVICE 8
#define ME_ERROR_NO_SUCH_COMMAND 9
#define ME_ERROR_RES_LAKE 10
#define ME_ERROR_DISPATCHER_NOT_RUNNING 11
#define ME_ERROR_NO_SUCH_DISPATCHER 12
#define ME_ERROR_DISPATCHERID_CONFILT 13
#define ME_ERROR_DISPATCHERID_STOPPED 14
#define ME_ERROR_CONFIG_NOT_ALLOWED 15
#define ME_ERROR_COMMU_WITH_KERNEL_NODE_FAILED 16
#define ME_ERROR_MSG_BLOCK_TOO_LONG 17
#define ME_ERROR_MSG_BLOCK_MISMATCH 18
#define ME_ERROR_MSG_DISPATCH_FAILED 19
#define ME_ERROR_MSG_MISMATCH 20
#define ME_ERROR_COPY_MEM_FROM_USERSPACE_FAILED 21
#define ME_ERROR_NO_MESSAGE 22
#define ME_ERROR_COPY_MEM_TO_USERSPACE_FAILED 23

#endif
